const types = {
  ADD_ADDRESS: "ADD_ADDRESS",
  EDIT_ADDRESS: "EDIT_ADDRESS",
  SAVE_ADDRESSES: "SAVE_ADDRESSES",
  SET_SELECTED_DELIVERY_ADDRESS: "SET_SELECTED_DELIVERY_ADDRESS",
  SET_SELECTED_PAYMENT_METHOD: "SET_SELECTED_PAYMENT_METHOD",
};

export default types;
