const types = {
  SET_USER: 'SET_USER',
  SET_LOGGED: 'SET_LOGGED',
  CHANGE_POSITION: 'CHANGE_POSITION',
  CART_ADD: 'CART_ADD',
  CART_REMOVE: 'CART_REMOVE',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM'
};

export default types;
